name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - Developers-Branch

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Checkout source code
        uses: actions/checkout@master

      - name: Install
          run: npm install

      - name: Lint
          run: npm run lint

      - name: Test
          run: npm run test:unit

      - name: Build
          run: npm run build

      - name: deploy to Server
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
            username: ${{ secrets.HOST_USERNAME }}
            server: ${{ secrets.HOST_IP }}
            ssh_private_key: ${{ secrets.EC2_SSH_KEY }}
            local_path: './dist/*'
            remote_path: ${{ secrets.HOST_TARGET_DIR_CURRENT }}
            sftp_only: true

